CREATE TABLE [dbo].[datahardware] (
    [Id]                         INT             IDENTITY (1, 1) NOT NULL,
    [tipo_hardware]              NVARCHAR (MAX)  NULL,
    [marca_hardware]             NVARCHAR (MAX)  NULL,
    [modello_hardware]           NVARCHAR (MAX)  NULL,
    [serie_hardware]             NVARCHAR (MAX)  NULL,
    [anno_hardware]              NVARCHAR (MAX)  NULL,
    [stato_hardware]             NVARCHAR (MAX)  NULL,
    [inventario_hardware]        NVARCHAR (MAX)  NULL,
    [foto_hardware]              VARBINARY (MAX) NULL,
    [pccollegato_hardware]       NVARCHAR (MAX)  NULL,
    [datainserimento_hardware]   NVARCHAR (MAX)  NULL,
    [orainserimento_hardware]    NVARCHAR (MAX)  NULL,
    [note_hardware]              NVARCHAR (MAX)  NULL,
    [autoreinserimento_hardware] NVARCHAR (MAX)  NULL,
    [FileName]                   NVARCHAR (MAX)  NULL,
    [FileSize]                   NVARCHAR (MAX)  NULL,
    [BinaryData]                 VARBINARY(MAX)     NULL,
    [ContentType]                NVARCHAR (MAX)  NULL,
    [cartella_hw]                NVARCHAR (MAX)  NULL,
    [dataora_ultimamodhw]        NVARCHAR (MAX)  NULL,
    [autore_ultimamodhw]         NVARCHAR (MAX)  NULL,
    [presidio_hw]                NVARCHAR (MAX)  NULL,
    [reparto_hw]                 NVARCHAR (MAX)  NULL,
    [padiglione_hw]              NVARCHAR (MAX)  NULL,
    [ip_hardware]                NVARCHAR (MAX)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

