CREATE TABLE [dbo].[datapc] (
    [Id]                     INT            IDENTITY (1, 1) NOT NULL,
    [nome_dominio_pc]        NVARCHAR (MAX) NULL,
    [dominio_pc]             NVARCHAR (MAX) NULL,
    [marca_pc]               NVARCHAR (MAX) NULL,
    [modello_pc]             NVARCHAR (MAX) NULL,
    [serie_pc]               NVARCHAR (MAX) NULL,
    [inventario_pc]          NVARCHAR (MAX) NULL,
    [reparto_pc]             NVARCHAR (MAX) NULL,
    [stanza_pc]              NVARCHAR (MAX) NULL,
    [inserito_da]            NVARCHAR (MAX) NULL,
    [padiglione_pc]          NVARCHAR (MAX) NULL,
    [piano_pc]               NVARCHAR (MAX) NULL,
    [presidio_pc]            NVARCHAR (MAX) NULL,
    [so_pc]                  NVARCHAR (MAX) NULL,
    [ram_pc]                 NVARCHAR (MAX) NULL,
    [processore_pc]          NVARCHAR (MAX) NULL,
    [indirizzo_ip_pc]        NVARCHAR (MAX) NULL,
    [swprivate_pc]           NVARCHAR (MAX) NULL,
    [data_ins_pc]            NVARCHAR (MAX) NULL,
    [ora_ins_pc]             NVARCHAR (MAX) NULL,
    [note_pc]                NVARCHAR (MAX) NULL,
    [stato_pc]               NVARCHAR (MAX) NULL,
    [anno_pc]                NVARCHAR (MAX) NULL,
    [id_stampante_collegata] NVARCHAR (MAX) NULL,
    [tipo_pc]                NVARCHAR (MAX) NULL,
    [marca_video_pc]         NVARCHAR (MAX) NULL,
    [modello_video_pc]       NVARCHAR (MAX) NULL,
    [pollici_video_pc]       NVARCHAR (MAX) NULL,
    [inventario_video_pc]    NVARCHAR (MAX) NULL,
    [serie_video_pc]         NVARCHAR (MAX) NULL,
    [note_video_pc]          NVARCHAR (MAX) NULL,
    [stato_video_pc]         NVARCHAR (MAX) NULL,
    [id_altrohw_collegato]   NVARCHAR (MAX) NULL,
    [anno_video_pc]          NVARCHAR (MAX) NULL,
    [FileName]               NVARCHAR (MAX) NULL,
    [FileSize]               NVARCHAR (MAX) NULL,
    [BinaryData]             VARBINARY(MAX)    NULL,
    [ContentType]            NVARCHAR (MAX) NULL,
    [autore_ultimapc]        NVARCHAR (MAX) NULL,
    [dataora_ultimapc]       NVARCHAR (MAX) NULL,
    [cartella_pc]            NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

