CREATE TABLE [dbo].[Utenti] (
    [Id]                    INT             IDENTITY (1, 1) NOT NULL,
    [matricola_utente]      NVARCHAR (MAX)  NULL,
    [nomeutente]            NVARCHAR (MAX)  NULL,
    [password]              NVARCHAR (MAX)  NULL,
    [sfondo]                NVARCHAR (MAX)  NULL,
    [foto_utente]           NVARCHAR (MAX)  NULL,
    [tipo_utente]           NVARCHAR (MAX)  NULL,
    [dettagli_utente]       NVARCHAR (MAX)  NULL,
    [database_utente]       NVARCHAR (MAX)  NULL,
    [creato_da]             NVARCHAR (MAX)  NULL,
    [ubicazione_utente]     NVARCHAR (MAX)  NULL,
    [data_creazione_utente] NVARCHAR (MAX)  NULL,
    [ora_creazione_utente]  NVARCHAR (MAX)  NULL,
    [data_modifica]         NVARCHAR (MAX)  NULL,
    [note_utente]           NVARCHAR (MAX)  NULL,
    [stato_utente]          NVARCHAR (MAX)  NULL,
    [autore_modifica]       NVARCHAR (MAX)  NULL,
    [ora_modifica]          NVARCHAR (MAX)  NULL,
    [FileName]              NVARCHAR (MAX)  NULL,
    [FileSize]              NVARCHAR (MAX)  NULL,
    [ContentType]           NVARCHAR (MAX)  NULL,
    [BinaryData]            VARBINARY (MAX) NULL,
    [paging]                NVARCHAR (MAX)  NULL,
    [cognome]               NVARCHAR (MAX)  NULL,
    [nome]                  NVARCHAR (MAX)  NULL,
    [email]                 NVARCHAR (MAX)  NULL,
    [lingua]			    NVARCHAR(MAX) NULL, 
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

